"""Publishing a generated repo to GitHub (spec decision D16).

Permission-dependent by design: with a token we create the repository and push;
without one the developer gets a zip and pushes it themselves. Both paths are
first-class — the product must be fully usable by someone who will not hand a
token to a local web app.

The token is used for the duration of a single push and never written to disk.
Git would otherwise persist it inside `.git/config` via the remote URL, so the
remote is rewritten to a clean URL immediately after the push.
"""

from __future__ import annotations

import io
import json
import subprocess
import urllib.error
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path

GITHUB_API = "https://api.github.com"


class PublishError(RuntimeError):
    """A publish step failed in a way the developer needs to see."""


@dataclass
class PublishResult:
    repo_url: str
    clone_url: str
    branch: str
    created: bool


def _api(path: str, token: str, payload: dict | None = None, method: str = "GET") -> dict:
    request = urllib.request.Request(
        f"{GITHUB_API}{path}",
        data=json.dumps(payload).encode() if payload is not None else None,
        method=method,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            "User-Agent": "ouroboros",
        },
    )
    try:
        with urllib.request.urlopen(request) as response:
            body = response.read().decode()
            return json.loads(body) if body else {}
    except urllib.error.HTTPError as error:
        detail = error.read().decode()[:400]
        # Never echo the token back in an error, whatever the API said.
        raise PublishError(f"GitHub API {error.code} on {path}: {detail}") from None
    except urllib.error.URLError as error:
        raise PublishError(f"Could not reach GitHub: {error.reason}") from None


def whoami(token: str) -> str:
    return _api("/user", token).get("login", "")


def ensure_repo(token: str, name: str, private: bool = True) -> tuple[str, bool]:
    """Return (clone_url, created). Reuses an existing empty repo of that name."""
    owner = whoami(token)
    if not owner:
        raise PublishError("The token did not identify a GitHub account.")

    try:
        existing = _api(f"/repos/{owner}/{name}", token)
        return existing["clone_url"], False
    except PublishError:
        pass

    created = _api(
        "/user/repos",
        token,
        payload={
            "name": name,
            "private": private,
            "description": "Agent harness repo generated by Ouroboros",
            "auto_init": False,
        },
        method="POST",
    )
    return created["clone_url"], True


def _git(*args: str, cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, check=False
    )


def push_directory(
    directory: Path,
    clone_url: str,
    token: str,
    branch: str = "main",
    message: str = "Initial harness repo generated by Ouroboros",
) -> None:
    """Initialise (if needed), commit everything, and push once."""
    directory = Path(directory)
    if not (directory / ".git").exists():
        if _git("init", "-q", cwd=directory).returncode != 0:
            raise PublishError("git init failed.")

    _git("checkout", "-B", branch, cwd=directory)
    _git("add", "-A", cwd=directory)

    if _git("status", "--porcelain", cwd=directory).stdout.strip():
        commit = _git("-c", "user.name=Ouroboros", "-c", "user.email=ouroboros@local",
                      "commit", "-m", message, cwd=directory)
        if commit.returncode != 0:
            raise PublishError(f"git commit failed: {commit.stderr[:300]}")

    authenticated = clone_url.replace("https://", f"https://x-access-token:{token}@")
    _git("remote", "remove", "origin", cwd=directory)
    _git("remote", "add", "origin", authenticated, cwd=directory)

    try:
        push = _git("push", "-u", "origin", branch, cwd=directory)
        if push.returncode != 0:
            raise PublishError(f"git push failed: {push.stderr.replace(token, '***')[:300]}")
    finally:
        # The token must not survive in .git/config.
        _git("remote", "set-url", "origin", clone_url, cwd=directory)


def publish(
    directory: Path, token: str, repo_name: str, private: bool = True, branch: str = "main"
) -> PublishResult:
    clone_url, created = ensure_repo(token, repo_name, private=private)
    push_directory(directory, clone_url, token, branch=branch)
    return PublishResult(
        repo_url=clone_url.removesuffix(".git"),
        clone_url=clone_url,
        branch=branch,
        created=created,
    )


def zip_directory(directory: Path) -> bytes:
    """The no-token path: hand back a scaffold the developer pushes themselves."""
    directory = Path(directory)
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(directory.rglob("*")):
            if path.is_file() and ".git" not in path.parts:
                archive.write(path, path.relative_to(directory).as_posix())
    return buffer.getvalue()
