"""Gap research and corpus write-back (spec decisions D7 / D9).

The corpus ships knowing how to build harnesses, not how to build every stack in
the world. When an interview names a stack we have no playbook for, we research
it once, write the findings back into the corpus as a normal curated document,
and every later project on that stack retrieves it instead of re-researching.

The corpus compounds. That is the whole point.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from pydantic import BaseModel, Field

from ouroboros.corpus.retriever import CORPUS_ROOT, CorpusDocument, FileCorpusRetriever
from ouroboros.inquisitor.prompts import STACK_RESEARCH
from ouroboros.llm.client import LLM
from ouroboros.models.spec import StackProfile, VerificationPlan

STACK_DOMAIN = "stack-playbooks"
STACK_DIR = "06-stack-playbooks"


class SkeletonFile(BaseModel):
    """One file in the minimal project skeleton."""

    path: str
    purpose: str
    contents: str = Field(description="Complete file contents, ready to write.")


class StackPlaybook(BaseModel):
    """Everything the Generator needs to emit a working repo for one stack."""

    language: str
    language_version: str
    framework: str | None = None
    package_manager: str

    install: str
    test: str
    lint: str | None = None
    typecheck: str | None = None
    build: str | None = None
    smoke: str | None = None

    layout_notes: list[str] = Field(
        default_factory=list, description="How projects on this stack are structured."
    )
    skeleton_files: list[SkeletonFile] = Field(default_factory=list)
    gotchas: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)

    def to_verification(self) -> VerificationPlan:
        return VerificationPlan(
            install=self.install,
            test=self.test,
            lint=self.lint,
            typecheck=self.typecheck,
            build=self.build,
            smoke=self.smoke,
        )


def stack_slug(stack: StackProfile) -> str:
    parts = [stack.language, stack.framework or "", stack.package_manager]
    raw = "-".join(p for p in parts if p).lower()
    cleaned = re.sub(r"[^a-z0-9]+", "-", raw).strip("-")
    return cleaned or "unknown-stack"


def find_playbook(retriever: FileCorpusRetriever, stack: StackProfile) -> CorpusDocument | None:
    """Return the existing playbook document for this stack, if we have one."""
    return retriever.get(stack_slug(stack))


def research_stack(llm: LLM, stack: StackProfile) -> StackPlaybook:
    """Produce a playbook for a stack the corpus does not yet cover."""
    described = (
        f"Language: {stack.language} {stack.language_version}\n"
        f"Framework: {stack.framework or 'none'}\n"
        f"Package manager: {stack.package_manager}\n"
        f"Database: {stack.database or 'none'}\n"
        f"Key libraries: {', '.join(stack.key_libraries) or 'none specified'}"
    )
    return llm.structured(
        StackPlaybook,
        system=STACK_RESEARCH,
        user=f"Produce the stack playbook for:\n\n{described}",
    )


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- None recorded."


def write_playbook_doc(
    playbook: StackPlaybook, root: Path | None = None
) -> Path:
    """Write a playbook into the corpus in the format every document follows."""
    root = root or CORPUS_ROOT
    stack = StackProfile(
        language=playbook.language,
        language_version=playbook.language_version,
        framework=playbook.framework,
        package_manager=playbook.package_manager,
    )
    directory = root / STACK_DIR
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stack_slug(stack)}.md"

    label = f"{playbook.language} {playbook.language_version}"
    if playbook.framework:
        label += f" / {playbook.framework}"

    commands = "\n".join(
        f"- `{name}`: `{cmd}`"
        for name, cmd in [
            ("install", playbook.install),
            ("test", playbook.test),
            ("lint", playbook.lint),
            ("typecheck", playbook.typecheck),
            ("build", playbook.build),
            ("smoke", playbook.smoke),
        ]
        if cmd
    )
    skeleton = "\n".join(
        f"- `{f.path}` — {f.purpose}" for f in playbook.skeleton_files
    ) or "- None recorded."

    document = f"""---
title: "{label} stack playbook"
source_url: ""
publisher: Ouroboros gap research
retrieved: {date.today().isoformat()}
domain: {STACK_DOMAIN}
doc_type: reference
relevance: "Verification commands and minimal skeleton for {label}, researched \
because the corpus had no coverage when a project requested this stack."
---

## Summary

Generated by Ouroboros gap research when a developer specified {label} and the
corpus had no playbook for it. It records the canonical verification commands
and the minimal project layout the Generator needs to emit a repository whose
`verify.sh` passes before any feature exists.

Machine-derived rather than sourced from a single document: treat the commands
as authoritative for generation, and correct this file if a real project on this
stack proves any of them wrong.

## Key knowledge

**Package manager:** `{playbook.package_manager}`

**Verification commands**

{commands}

**Layout**

{_bullets(playbook.layout_notes)}

**Skeleton files**

{skeleton}

**Gotchas**

{_bullets(playbook.gotchas)}

**Sources consulted**

{_bullets(playbook.sources)}

## Notable quotes

None — this document is machine-generated rather than sourced from prose.

## Application to Ouroboros

The Generator reads this playbook to emit `verify.sh`, `init.sh`, and the
project skeleton for this stack. Its presence is also what flips
`stack.corpus_covered` to true, which is what lets the ambiguity lint stop
refusing generation for this stack.
"""
    path.write_text(document, encoding="utf-8")
    return path


def ensure_playbook(
    llm: LLM, retriever: FileCorpusRetriever, stack: StackProfile, root: Path | None = None
) -> tuple[StackPlaybook | None, bool]:
    """Return (playbook, researched_now). Researches and writes back on a miss."""
    existing = find_playbook(retriever, stack)
    if existing is not None:
        return None, False

    playbook = research_stack(llm, stack)
    write_playbook_doc(playbook, root=root)
    return playbook, True
